server:
  applicationConnectors:
  - type: http
    port: 8082
  adminConnectors:
  - type: http
    port: 8083

syndicationHealthCheckUrl: http://localhost:8085
syndicationBaseUrl: http://localhost:8084
syndicationUri: /edges/to

oracleHealthCheckUrl: http://localhost:8085
oracleBaseUrl: http://localhost:8084
oracleUri: /product/%s/%s/sources

elasticSearchHealthCheckUrl: http://localhost:8085
elasticSearchBaseUrl: http://localhost:8084
elasticSearchUri: /explore